### ISSUE TITLE
cad outputs

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#77] opened 2021-03-04 17:20 UTC
1. Cad outputs are no longer on layers, they come in on layer 0, default unknown layer.

2. Can we standardize the layers to:
GOV-GIS-FEMA-BFP-AE
GOV-GIS-FEMA-BFP-VE
GOV-GIS-HAT
GOV-GIS-LIDAR 2FT CONTOUR
GOV-GIS-PARCEL
GOV-GIS-ROAD
GOV-GIS-SLOPE
 if not already established as listed above.  I'm defining my AutoCAD template to accept these specific layer names with preset 
  styles.

3. Also the layer tree is left expanded after this operation. 
![image](https://user-images.githubusercontent.com/1892068/110000727-9db06100-7ce1-11eb-9e88-05c6aaf4e9ff.png)

These are results from .75

**Comment by azithinkiam** [comment] 2021-03-04 18:03
Weird.  Leave it on tonight and I’ll see what’s up.  What specific jobs have you experienced this with?

**Comment by Cadmanick** [comment] 2021-03-04 18:07
JUST 20-391

**Comment by azithinkiam** [comment] 2021-03-07 15:26
RESOLVED.

1. This was also caused by the re-saving of the NWP file last month and I just missed it when I was fixing the other issue.  I had to replace the HAT/AE/VE layers with the .SHP versions that have the 'Layer' field (this is how the layer name is set) and re-save.
2. Layer names have been updated per request.  NOTE: this is achieved by adding an attribute column called 'Layer' (text) and setting the value to whatever you want the layer name displayed as ('GOV-GIS-ROAD').  This must be done for every layer in scope including all town-specific contour layers.
3. Added 'resetLegend(self)' at the end of the exportDXF class

please confirm at your convenience.  

NOTE: if a layer does not intersect, it will not be included in the merged export (slope).

**Closed by azithinkiam** 2021-03-07 15:26 UTC
Labels: bug
