### ISSUE TITLE
tool needed to move jobs to new or existing feature.

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#23] opened 2020-05-21 13:00 UTC
need file menu command to move jobs to new parcel or from parcel to line or vice versa, including error checking.
The first candidate is to move job 18-383 from adjacent parcels to roadline of Atlantic Ave. adjacent...

**Comment by azithinkiam** [comment] 2020-05-21 15:06
duplicate of #22

**Closed by azithinkiam** 2020-05-21 15:06 UTC
Labels: duplicate
