### ISSUE TITLE
PENDING | (Unable to Reproduce) | ISSUE: Qgis will not shut down.

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#43] opened 2020-07-27 15:07 UTC
Is there anything that can be done for the subject issue?  This is crippling our job setup workflow.  is it something we are doing?  you mentioned that something was remaining open on the server?  is this something than can be fixed?

**Comment by Cadmanick** [comment] 2020-07-27 15:12
Issue is happening on most machines.  Most users will not use the program any longer due to this.  therefore the only 3 i know which still have the problem are i9, office & office-2.  i get a db_exec warning when or during the session when it will happen upon attempting to close...
I know that QGIS makes a server product.  Should i be serving up some of my layers instead of just grabbing shp files from folders on the z drive?  This comment is related to the other request of serving raster layers.   how can i tell what layer is the bad seed if it is just a layer hanging up?

**Comment by azithinkiam** [comment] 2020-07-27 16:08
It’s something to do with one (or more) of the layers in your NWP file.  I may have to start pulling them out one by one to find it, so this is why I asked you to go through and make sure everything included in your file was needed for the others.  Now that we’ve updated all QGS files with your base version, they all seem to have picked up the issue.

 

1.	Why do they need to close QGIS?  It should be open all day, every day

 

I know it’s annoying, but it’s hardly something that should make people stop using it…it’s not used when it’s closed…so just leave it open and don’t shut the damn machines down every night.  Workaround: achieved.

**Comment by Cadmanick** [comment] 2020-07-27 19:01
i guess i have shot us in the foot!  my layers are simply a compiled, comprehensiveish, list of layers for the task of running this buisness.  i could lose the baseline, ngs control adn spcszn83-2 layers in all others.  They are layers i prefer to keep since they assist me in various task i'm requested to do.  likewise i don't think the image layers "ESRI...", "USGS...", "USA..." & "World_map_topo" could go since they are simply backup layers i use when other imagery and topo layers are not available...  otherwise the only other layers that the other users didn't have were the "town" layers...  we could start troubleshooting here with the qgis of others, not mine please.

**Comment by azithinkiam** [comment] 2020-07-27 23:18
Apparently it could be related to geopackage layers.  I’ve seen a few other reports of the same problem with GPKGs but no clear fix. 

 

Every time you open one QGS file, it opens around 150 unique other files…some of those end up with locks on them (not sure how yet) and that’s likely what keeps you from closing. 

 

I can’t reproduce it easily…can really only come in behind you and see the problem and fix it by closing open files from the server.  

 

Gonna have to reproduce consistently before I can do much troubleshooting on this.

**Comment by Cadmanick** [comment] 2020-07-28 11:44
might this be related?  on .75 upon login this am and others recently
![image](https://user-images.githubusercontent.com/1892068/88660907-9965fa80-d0a5-11ea-9855-5185708dc653.png)

messages:
2020-07-28T07:39:53     WARNING    Authentication Manager : Auth db query exec() FAILED
2020-07-28T07:39:58     WARNING    Authentication Manager : Auth db query exec() FAILED
2020-07-28T07:40:10     WARNING    Authentication Manager : Auth db query exec() FAILED

Python warnings:
2020-07-27T16:24:42     WARNING    warning:C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages\PyQt5\uic\objcreator.py:152: DeprecationWarning:
             
             'U' mode is deprecated
             
             
             traceback: File "", line 1, in 
              File "C:/PROGRA~1/QGIS3~1.2/apps/qgis/./python\qgis\utils.py", line 337, in startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "Z:\0 - Settings\GIS\QGIS\plugins\profiles\default/python/plugins\MapsPrinter\__init__.py", line 34, in classFactory
              from .maps_printer import MapsPrinter
              File "C:/PROGRA~1/QGIS3~1.2/apps/qgis/./python\qgis\utils.py", line 674, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 961, in _find_and_load
              File "", line 950, in _find_and_load_unlocked
              File "", line 655, in _load_unlocked
              File "", line 678, in exec_module
              File "", line 205, in _call_with_frames_removed
              File "Z:\0 - Settings\GIS\QGIS\plugins\profiles\default/python/plugins\MapsPrinter\maps_printer.py", line 42, in 
              from .maps_printer_dialog import MapsPrinterDialog
              File "C:/PROGRA~1/QGIS3~1.2/apps/qgis/./python\qgis\utils.py", line 674, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 961, in _find_and_load
              File "", line 950, in _find_and_load_unlocked
              File "", line 655, in _load_unlocked
              File "", line 678, in exec_module
              File "", line 205, in _call_with_frames_removed
              File "Z:\0 - Settings\GIS\QGIS\plugins\profiles\default/python/plugins\MapsPrinter\maps_printer_dialog.py", line 29, in 
              os.path.dirname(__file__), 'maps_printer_dialog_base.ui'))
              File "C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages\PyQt5\uic\__init__.py", line 198, in loadUiType
              winfo = compiler.UICompiler().compileUi(uifile, code_string, from_imports, resource_suffix, import_from)
              File "C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages\PyQt5\uic\Compiler\compiler.py", line 53, in __init__
              qtproxies.QtWidgets, CompilerCreatorPolicy())
              File "C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages\PyQt5\uic\uiparser.py", line 167, in __init__
              self.factory = QObjectCreator(creatorPolicy)
              File "C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages\PyQt5\uic\objcreator.py", line 85, in __init__
              if self.load_plugin(filename, plugin_globals, plugin_locals):
              File "C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages\PyQt5\uic\objcreator.py", line 152, in load_plugin
              plugin = open(filename, 'rU')
             
postgis:
2020-07-28T07:39:47     WARNING    NOTICE: row number 0 is out of range 0..-1

general:
2020-07-27T16:24:36     INFO    QGIS starting…
2020-07-27T16:24:37     INFO    Python support ENABLED :-) 
2020-07-27T16:24:47     INFO    Application state:
             QGIS_PREFIX_PATH env var: C:/PROGRA~1/QGIS3~1.2/apps/qgis
             Prefix: C:/PROGRA~1/QGIS3~1.2/apps/qgis
             Plugin Path: C:/PROGRA~1/QGIS3~1.2/apps/qgis/plugins
             Package Data Path: C:/PROGRA~1/QGIS3~1.2/apps/qgis/.
             Active Theme Name: default
             Active Theme Path: C:/PROGRA~1/QGIS3~1.2/apps/qgis/./resources/themes\default\icons/
             Default Theme Path: :/images/themes/default/
             SVG Search Paths: C:/PROGRA~1/QGIS3~1.2/apps/qgis/./svg/
              Z:\0 - Settings\GIS\QGIS\plugins\profiles\default/svg/
             User DB Path: C:/PROGRA~1/QGIS3~1.2/apps/qgis/./resources/qgis.db
             Auth DB Path: Z:\0 - Settings\GIS\QGIS\plugins\profiles\default/qgis-auth.db
             
2020-07-27T16:24:47     INFO    QGIS Ready!
2020-07-28T07:40:27     WARNING    Primary key is ctid - changing of existing features disabled (; "public"."parcels_aux")

**Comment by azithinkiam** [comment] 2020-07-28 15:13
Nope, that’ s something wrong with a plugin called “maps printer” that has apparently been added to the default profile:

 

File "Z:\0 - Settings\GIS\QGIS\plugins\profiles\default/python/plugins\MapsPrinter\__init__.py", line 34, in classFactory
 
          from .maps_printer import MapsPrinter
 

Did you add this?  It looks like it’s not working…and at that point you don’t have any QGIS file open.

 

Please have all machines use QGIS today and leave it open and leave them on tonight.  I need as many options as possible to try to figure out which of the layers is causing the issue.  

 

There’s no reason you need to use GPKG layers is there?  If we can get them into SHPs or the DB or something, would that work?  As long as you have the data from those layers available?

 

-t.

**Comment by Cadmanick** [comment] 2020-07-28 17:00
ok, it's wes' 3rd birthday today and the kids are sick, so i have to leave early to help out.  i will tell the ladies to leave their pc's on.  min will be available at 1:00 pm..  you can remove that stuff from my pc if it will help.  i dont' use it.

i only used geopackage on a few jobs since i thought it was more compatible with qgis than shp, guess i was wrong... so figure out which i need to convert and i will...

**Comment by azithinkiam** [comment] 2020-11-11 21:53
removed offending layers from project files.  issue has not returned in several months.

**Closed by azithinkiam** 2020-11-11 21:53 UTC
Labels: annoyance
